ERROR 2021-01-05 17:54:28,081: report_part_c.docx does not exist.
INFO 2021-01-05 17:54:28,113: Successfully loaded benchmark labels data.
INFO 2021-01-05 17:54:28,116: Successfully loaded queries data.
ERROR 2021-01-05 17:54:28,117: search_engine_1.py does not exist.
ERROR 2021-01-05 17:54:28,118: search_engine_2.py does not exist.
INFO 2021-01-05 17:54:32,608: Successfully imported module search_engine_best.
INFO 2021-01-05 17:54:32,608: loading Word2VecKeyedVectors object from word2vec.wordvectors
DEBUG 2021-01-05 17:54:32,609: {'uri': 'word2vec.wordvectors', 'mode': 'rb', 'buffering': -1, 'encoding': None, 'errors': None, 'newline': None, 'closefd': True, 'opener': None, 'ignore_ext': False, 'transport_params': None}
INFO 2021-01-05 17:54:32,815: setting ignored attribute vectors_norm to None
INFO 2021-01-05 17:54:32,815: loaded word2vec.wordvectors
DEBUG 2021-01-05 17:54:37,894: Building the index in search_engine_best for benchmark data took 5.043402660000001 seconds.
INFO 2021-01-05 17:54:37,895: loading Word2VecKeyedVectors object from ./model
DEBUG 2021-01-05 17:54:37,895: {'uri': './model', 'mode': 'rb', 'buffering': -1, 'encoding': None, 'errors': None, 'newline': None, 'closefd': True, 'opener': None, 'ignore_ext': False, 'transport_params': None}
ERROR 2021-01-05 17:54:37,895: The following error occured while testing the module search_engine_best.
ERROR 2021-01-05 17:54:37,895: [Errno 2] No such file or directory: './model'
Traceback (most recent call last):
  File "/Users/ariel-pc/Documents/שנה ג/IR/Part 3/Search_Engine/test_part_c_students.py", line 107, in <module>
    engine.load_precomputed_model(model_dir)
  File "/Users/ariel-pc/Documents/שנה ג/IR/Part 3/Search_Engine/search_engine_best.py", line 67, in load_precomputed_model
    return KeyedVectors.load(model_dir, mmap='r')
  File "/Users/ariel-pc/Documents/שנה ג/IR/Part 3/Search_Engine/venv/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 1553, in load
    model = super(WordEmbeddingsKeyedVectors, cls).load(fname_or_handle, **kwargs)
  File "/Users/ariel-pc/Documents/שנה ג/IR/Part 3/Search_Engine/venv/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 228, in load
    return super(BaseKeyedVectors, cls).load(fname_or_handle, **kwargs)
  File "/Users/ariel-pc/Documents/שנה ג/IR/Part 3/Search_Engine/venv/lib/python3.7/site-packages/gensim/utils.py", line 435, in load
    obj = unpickle(fname)
  File "/Users/ariel-pc/Documents/שנה ג/IR/Part 3/Search_Engine/venv/lib/python3.7/site-packages/gensim/utils.py", line 1395, in unpickle
    with open(fname, 'rb') as f:
  File "/Users/ariel-pc/Documents/שנה ג/IR/Part 3/Search_Engine/venv/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 181, in open
    newline=newline,
  File "/Users/ariel-pc/Documents/שנה ג/IR/Part 3/Search_Engine/venv/lib/python3.7/site-packages/smart_open/smart_open_lib.py", line 340, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: './model'
DEBUG 2021-01-05 17:54:37,904: Total runtime was: 0:00:09.822977
